### ISSUE TITLE
Rebuild to work on a specific IP errors

### ISSUE THREAD

**Issue by UrbanSide** [Supertigerr/better-in-game-chat#3]
Hello, I really liked your project, how can I rebuild it so that it automatically connects to the IP of my vps? Without unnecessary commands?
I have this error on run pack/dist
```
"C:\Program Files\nodejs\npm.cmd" run dist

> client@1.3.1 dist
> electron-builder

  • electron-builder  version=23.6.0 os=10.0.22000
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=extract-file-icon@0.3.2, forcefocus@1.1.0, node-window-manager@2.2.4, uiohook-napi@1.5.2 platform=win32 arch=x64
  • install prebuilt binary  name=forcefocus version=1.1.0 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=forcefocus
                                          version=1.1.0
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=C:\Users\Dael\Downloads\client\node_modules\prebuild-install\node_modules\node-abi\index.js:36
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 20.3.12 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (C:\Users\Dael\Downloads\client\node_modules\prebuild-install\node_modules\node-abi\index.js:36:9)
        at module.exports (C:\Users\Dael\Downloads\client\node_modules\prebuild-install\rc.js:73:57)
        at Object.<anonymous> (C:\Users\Dael\Downloads\client\node_modules\prebuild-install\bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1256:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
        at Module.load (node:internal/modules/cjs/loader:1119:32)
        at Module._load (node:internal/modules/cjs/loader:960:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:23:47

    Node.js v18.17.1
```

**Comment by SupertigerDev** [comment]
Hello, once you set the IP, you shouldn't need to update it again. Anyway that error is strange. Maybe you need to update nom packages? Not sure, I'll see when I'm available.

**Comment by UrbanSide** [comment]
> Hello, once you set the IP, you shouldn't need to update it again. Anyway that error is strange. Maybe you need to update nom packages? Not sure, I'll see when I'm available.

Thank you, and another problem is that it intercepts the game window after sending a message, the game hangs until you press alt+tab
For some reason, my friend’s commands and messages are generally not sent, although the chat works and connects to the server.

**Comment by SupertigerDev** [comment]
Strange, not 100% sure to be honest. Haven't worked on this project for years. By command not being sent, what do you mean? Does it just not do anything when running those commands?

**Comment by UrbanSide** [comment]
Yes, he entered, for example, “Hello”, pressed Enter and nothing happened, and this happened after changing the key to open the chat. Now he can’t send a message or a command)

**Comment by SupertigerDev** [comment]
Maybe some kind of conflict is happening after changing the keybind. Your friend might have to uninstall and install the overlay again

**Comment by UrbanSide** [comment]
> Maybe some kind of conflict is happening after changing the keybind. Your friend might have to uninstall and install the overlay again

he already reinstalled, everything is the same ((It’s a shame, because in a couple of games where we play, the chat is terrible...

**Comment by SupertigerDev** [comment]
seems like reinstalling doesnt remove the config files. tell your friend to go to %appdata% client/config.json and see what the keybind is set to. and also to delete the config file and reopen the overlay

**Comment by UrbanSide** [comment]
@SupertigerDev 
![image](https://github.com/SupertigerDev/better-in-game-chat/assets/26259129/c671d2b5-f0e0-45aa-a93d-6611d4af6534)
We found a new “squiggle” when opening the chat, as if the game freezes for 5-10 seconds. But if you open the UI in the game where the cursor is shown, then everything is ok.

P.S I agree, screenshot is a bad idea))

**Comment by UrbanSide** [comment]
From what I understand so far, this is conditionally due to the loss of focus of the game. But I haven’t figured out how to win yet...
